# Generated by Django 5.1.5 on 2025-02-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='special_role',
            field=models.BooleanField(default=False),
        ),
    ]
