# Generated by Django 5.1.5 on 2025-02-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_special_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='special_role',
            new_name='role',
        ),
    ]
