name: Dispatch Update Submodule
on:
  push:
    branches:
      - master
jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dispatch update to Git Blog Project
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: Codeminister2137/tsk
          event-type: update-submodule